name: enum_string_value_lib
description: It's append String expressions/values for your own enum classes!
version: 1.0.0+1
homepage: https://github.com/kikuchy/enum_string_value

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
