builders:
  enum_string_value:
    import: "package:enum_string_value_generator/enum_string_value_generator.dart"
    builder_factories: ["enumHasValueBuilder"]
    build_extensions: {".dart": [".value.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]