name: enum_string_value_generator
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: kikuchy <kikuchy.h@gmail.com>

environment:
  sdk: '>=2.6.0-dev.0.0 <3.0.0'

dependencies:
  build: ^1.2.2
  analyzer: ^0.39.1
  source_gen: ^0.9.4+6
  code_builder: ^3.2.1
  enum_string_value_lib:
    path: ../enum_string_value_lib

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
