name: enum_string_value_generator
description: It's append String expressions/values for your own enum classes!
version: 0.0.2+1
homepage: https://github.com/kikuchy/enum_string_value

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  build: ^1.2.2
  analyzer: ^0.38.5
  source_gen: ^0.9.4+6
  code_builder: ^3.2.1
  enum_string_value_lib: ^1.0.0+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
