name: enum_string_value_generator
description: Now your enum classes have String values!!
version: 0.0.1+1
homepage: https://github.com/kikuchy/enum_string_value
author: kikuchy <kikuchy.h@gmail.com>

environment:
  sdk: '>=2.6.0-dev.0.0 <3.0.0'

dependencies:
  build: ^1.2.2
  analyzer: ^0.39.0
  source_gen: ^0.9.4+6
  code_builder: ^3.2.1
  enum_string_value_lib: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
